# games-antibot v0.1 file configuration.

plugin-prefix: 'Antibot'

messages:
  impossible-check: 'Impossivel validar sua sessao, tente novamente.'
  debug-connection-bot: 'O IP "<ip>" foi identificado como bot e esta permanentemente banido do servidor.'

mysql:
  host: localhost
  db: redeshield
  port: 3306
  user: root
  pass: