# games-antibot v0.1 file configuration.

plugin-prefix: 'Antibot'

messages:
  impossible-check: 'Impossivel validar sua sessao, tente novamente.'

mysql:
  host: localhost
  db: redeshield
  port: 3306
  pass: